export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS';
export const SET_OLDER_NOTIFICATIONS = 'SET_OLDER_NOTIFICATIONS';
export const SET_NOTIFICATION_COUNT = 'SET_NOTIFICATION_COUNT';
export const SET_NEXT_CURSOR = 'SET_NEXT_CURSOR';
