export const SET_USER_INFO = 'SET_USER_INFO';
export const SET_MODELS = 'SET_MODELS';
export const SET_DEFECTS = 'SET_DEFECTS';
export const SET_MODELS_LOADING = 'SET_MODELS_LOADING';
export const SET_DEFECTS_LOADING = 'SET_DEFECTS_LOADING';
export const SET_USER_INFO_LOADING = 'SET_USER_INFO_LOADING';
export const SET_USE_CASE = 'SET_USE_CASE';
export const SET_USE_CASE_LOADING = 'SET_USE_CASE_LOADING';
